using Shared.GameLogic;
using System.Net.Sockets;

namespace Shared.Network
{
    public enum SessionState
    {
        Connected, // after TCP  finish hand-shake 3 step
        Disconnected, 
        Authenticated, // after login
        InGame
    } 


    /// <summary>
    /// Represents a single client connection (ONE TCP CONNECTION).
    /// Responsible ONLY for network communication and session state.
    /// </summary>
    public class Session : IDisposable
    {
        /// <summary>
        /// Unique ID generated by server to identify this connection.
        /// Exists only while the client is connected.
        /// </summary>
        public int SessionId { get; private set; }

        /// <summary>
        /// Underlying TCP client representing the socket connection.
        /// </summary>
        private TcpClient _tcpClient;

        /// <summary>
        /// Network stream used for sending and receiving raw bytes.
        /// </summary>
        private NetworkStream _stream;

        /// <summary>
        /// Current session state (Connected, Authenticated, InGame, etc).
        /// </summary>
        public SessionState State { get; private set; }

        /// <summary>
        /// Reference to the authenticated player.
        /// Assigned AFTER successful login.
        /// </summary>
        public Player Player { get; private set; }

        /// <summary>
        /// Token used to cancel receive/send loops on disconnect.
        /// </summary>
        private CancellationTokenSource _cts = new();

        private PacketReader _packetReader;

        public event Action<Session, Packet> OnPacketReceived;
        public event Action<Session> OnClosed;

        public Session()
        {
            
        }

        public void Start(int sessionId, TcpClient tcpClient)
        {
            SessionId = sessionId;
            _tcpClient = tcpClient;
            _stream = tcpClient.GetStream();
            _cts = new CancellationTokenSource();

            State = SessionState.Connected;

            Task.Run(() => ReceiveLoopAsync());
        }

        /// <summary>
        /// Closes the session and releases all network resources.
        /// </summary>
        public void Close()
        {
            if (State == SessionState.Disconnected)
                return;

            State = SessionState.Disconnected;
            _cts.Cancel();

            _stream?.Close();
            _tcpClient?.Close();

            OnClosed?.Invoke(this);
        }

        public void Dispose()
        {
            Close();
            _cts.Dispose();
        }

        /// <summary>
        /// Binds a player to this session after authentication.
        /// </summary>
        public void BindPlayer(Player player)
        {
            Player = player;
            State = SessionState.Authenticated;
        }

        public void SendPacket(Packet packet) 
        {
            if ( !_tcpClient.Connected) return;

            uint length = (uint)(PacketReader.LENGTH_SIZE + PacketReader.PACK_HEADER_SIZE + packet.Data.Length);
            byte[] bytes = new byte[length];
            int offset = 0;
            Array.Copy(BitConverter.GetBytes(length), 0, bytes, offset, 4);
            offset += 4;
            Array.Copy(StructByteConverter.ToBytes(packet.Header), 0, bytes, offset, PacketReader.PACK_HEADER_SIZE);
            offset += 4;
            Array.Copy(packet.Data, 0, bytes, offset, packet.Data.Length);

            _stream.Write(bytes, 0, bytes.Length);
            _stream.Flush();

        }

        public void SendCmd<T>(EPacketHeader header, T value) where T : struct
        {
            var packet = new Packet
            {
                Header = header,
                Data = StructByteConverter.ToBytes(value)
            };

            SendPacket(packet);
        }


        /// <summary>
        /// Starts asynchronous loop for receiving data from client.
        /// Only reads bytes and forwards them to packet processor.
        /// </summary>
        protected async Task ReceiveLoopAsync()
        {
            _packetReader = new PacketReader();

            try
            {
                while (!_cts.IsCancellationRequested)
                {
                    bool valid = await _packetReader.ReadAsync(_stream, OnReadedPacket, _cts.Token);
                    if (!valid) break;
                }
            }
            catch (OperationCanceledException)
            {
                // Expected on disconnect
                Close();
            }
            catch (Exception ex)
            {
                //Logger.LogError($"Session {SessionId} error: {ex}");
                Close();
            }
            finally
            {
                Close();
            }
        }

        protected void OnReadedPacket(Packet packet)
        {
            OnPacketReceived?.Invoke(this, packet);
        }

        
    }


}
